✨ [FEAT] 목표 재사용 셀 만들기
TeamPOME/POME-iOS pull request #12
Opened 2022-07-08 13:55 UTC by yujindonut

## 🍎 관련 이슈
closed #4

## 🍎 변경 사항 및 이유

목표 재사용 셀을 코드베이스로 생성했습니다. 

- 폴더위치 
- Mypage / Cell / TVC / GoalStorageTVC.swift
<img width="271" alt="image" src="https://user-images.githubusercontent.com/78431728/178004455-15d7334a-4ef5-4756-ab75-b025a7850c73.png">

## 🍎 PR Point

- 제프린 뷰와 피그마 뷰가 살짝 달라서 ! 우선 보이는 UI는 모두 생성해두었고, 확정되는 뷰가 나옴에 따라 변경하면 좋을 것 같습니다! 

- 제플린
<img width="473" alt="image" src="https://user-images.githubusercontent.com/78431728/178004197-e3b262b0-f5c5-464c-aba1-52191f969b03.png">

- 피그마
<img width="409" alt="image" src="https://user-images.githubusercontent.com/78431728/178004234-40a8985b-4a25-4a52-9c0d-a8645dd26333.png">

- 피그마랑 제프린이랑 다른 제목 라벨 부분은 아래의 것입니다.

<img width="54" alt="image" src="https://user-images.githubusercontent.com/78431728/178006901-ab014004-ef31-4dd9-b121-2a99fe57a8ee.png">

```Swift
//라벨을 감싸고 있는 컨테이너 뷰
    private let ifSuccessLabelContainerView = UIView().then {
        $0.makeRounded(cornerRadius: 8)
        $0.backgroundColor = .grey_5
        $0.clipsToBounds = true
    }
 //컨테이너 뷰 안에 들어가는 UILabel
    private let ifSuccessLabel = UILabel().then {
        $0.setLabel(text: "gggg", color: .white, size: 10, weight: .semiBold)
        $0.textAlignment = .center
    }

```

<img width="60" alt="image" src="https://user-images.githubusercontent.com/78431728/178007320-aba2e3cf-4e8c-42d4-b847-b5b0d4d642e1.png">

```Swift
//progress와 붙어있는 비율 라벨 이라는 .. 뜻..
    private let progressPercentageLabel = UILabel().then {
        $0.setLabel(text: "", color: .white, size: 12, weight: .semiBold)
    }

    //비율 라벨을 품은 컨테이너 뷰라는 뜻..
    private let percentageContainerView = UIView().then {
        $0.makeRounded(cornerRadius: 10)
        $0.clipsToBounds = true
    }

```

여기서 progress바를 변경해주면서 저 라벨 부분의 색과 글씨도 변경합니다

```Swift
    private func setProgress(goal: Double) {
        if goal > 100 {
            progress = 100
            progressView.backgroundColor = .red
            percentageContainerView.backgroundColor = .red
            progressPercentageLabel.text = "초과"
        }
        else {
            progress = goal
            progressView.backgroundColor = .main
            percentageContainerView.backgroundColor = .main
            progressPercentageLabel.text = String(format: "%.f", progress) + "%"
        }
        // 데이터에 따라 progressView를 다시
        updateProgressView()
    }

```

- 코드 적용 방법
Cell과 Model을 연결할 수 있는 부분을 설정하였습니다.

```Swift

// MARK: - Network
extension GoalStorageTVC {
    
    //setData에서 값주기
    func setData(_ goalData: GoalDataModel) {
        goalTitleLabel.text = goalData.goalTitle
        ifSuccessLabel.text = goalData.ifSuccessOrNotLabelText
        moneyGoalLabel.text = goalData.goalMoneyLabel
        realSpentMoneyLabel.text = goalData.spentMoneyLabel
        setProgress(goal: goalData.successPercentage)
    }
}

```

- progress뷰를 값에 따라 update해주는 함수입니다. 

```Swift
     private func updateProgress(completion: @escaping () -> Void) {
        completion()
    }
    
    // 처음에 viewDidLoad의 값이 아닌 변경된 값을 보여줌
    private func updateProgressView() {
        updateProgress { [weak self] in
            self?.progressView.snp.remakeConstraints {
                $0.left.bottom.top.trailing.equalToSuperview()
                $0.width.equalToSuperview().multipliedBy((self?.progress ?? 100) / 100)
            }
        }
    }
    
    // progressbar의 값이 들어오면 초과, 퍼센트 판별
    private func setProgress(goal: Double) {
        if goal > 100 {
            progress = 100
            progressView.backgroundColor = .red
            percentageContainerView.backgroundColor = .red
            progressPercentageLabel.text = "초과"
        }
        else {
            progress = goal
            progressView.backgroundColor = .main
            percentageContainerView.backgroundColor = .main
            progressPercentageLabel.text = String(format: "%.f", progress) + "%"
        }
        // 데이터에 따라 progressView를 다시
        updateProgressView()
    }
```

- 뷰 컨트롤러에서 사용하는 방법

- BaseVC를 상속받은 클래스를 생성한다.

```Swift
class GoalStorageVC: BaseVC
```

상속받으면 은주가 만들어놓은 셀.register()함수를 쉽게 사용하려고 했으나 .. nib파일을 찾을 수 없다는 오류가 나와서 .. 우선 밑의 코드로 변경했습니다 .. !

```Swift
tableView.register(GoalStorageTVC.self, forCellReuseIdentifier: Identifiers.GoalStorageTVC)
```

셀 등록 겸 더미데이터 넣는 방법
Global파일에 Identifiers를 넣어두어서, 아래의 것을 사용하면 됩니다.

```Swift
Identifiers.GoalStorageTVC
```

- 예시 

```Swift
func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        
        guard let cell = tableView.dequeueReusableCell(withIdentifier: Identifiers.GoalStorageTVC, for: indexPath) as? GoalStorageTVC else { return UITableViewCell() }
        
        cell.setData(GoalDataModel.sampleData[indexPath.row])
        return cell
    }
```
## 📸 ScreenShot

<img width="326" alt="image" src="https://user-images.githubusercontent.com/78431728/178004116-5574d745-06f0-46b4-a48d-1878c0488e34.png">

2022-07-08 15:03 UTC, wngus4296 requested changes
코베.. 처음 맞으신지.. 왤케 잘해요 ~

전체적으로 컨벤션에 따라 마크 구문 말고 일반 주석은 /// 세 개로 변경해주세요!!
그리고 필요없는 빈 줄은 삭제하고, 주석 위에는 한 줄 띄워주면 좋을 것 같아요~~

고생하셨습니다 🤗

2022-07-08 15:03 UTC, wngus4296 commented on POME-iOS/POME-iOS/Screen/Mypage/Cell/TVC/GoalStorageTVC.swift
> +    override func setSelected(_ selected: Bool, animated: Bool) {
여기는 한 줄 띄우면 될 것 같아요!

2022-07-08 16:37 UTC, jane1choi requested changes
로직처리 짱 잘했네!!! 초과 판별을 서버에서 해서 줄수도 있을 것 같은데,,,
요건 나중에 API 나오면 다시봐보도록 하자! 그래도 넘 잘했음...짱짱!!
리뷰 확인한번 해조~!

2022-07-08 16:37 UTC, jane1choi commented on POME-iOS/POME-iOS/Global/Struct/Identifiers.swift
> +    static let GoalStorageTVC = "GoalStorageTVC"
Identifier 잘 추가했는데! 개인적으로는 목표 카드 셀이니까 `GoalCardTVC` 라는 네이밍이 좀 더 적절해보이는 것 같은데
네이밍에 대한 고민 좀 더 해봅시다..!!

2022-07-08 16:37 UTC, jane1choi commented on POME-iOS/POME-iOS/Screen/Mypage/Cell/TVC/GoalStorageDataModel.swift
> +struct GoalDataModel {
모델에 관련된 파일은 폴더링 컨벤션에서 정했듯이 PublicData > AppModel 파일에 위치시켜주세요!!

2022-07-08 16:37 UTC, jane1choi commented on POME-iOS/POME-iOS/Screen/Mypage/Cell/TVC/GoalStorageTVC.swift
> +    var progress = 1.0
요 변수도 다른 파일에서 쓰이지 않는 변수라면 `private` 으로 접근제어 해주는거 어떨까요??

2022-07-08 16:37 UTC, jane1choi commented on POME-iOS/POME-iOS/Screen/Mypage/Cell/TVC/GoalStorageTVC.swift
> +    }
굿굿 함수 재정의해서 잘했당!!!

2022-07-08 16:37 UTC, jane1choi commented on POME-iOS/POME-iOS/Screen/Mypage/Cell/TVC/GoalStorageTVC.swift
> +
요기 빈줄 삭제 해줍시다!

2022-07-08 16:37 UTC, jane1choi commented on POME-iOS/POME-iOS/Screen/Mypage/Cell/TVC/GoalStorageTVC.swift
> +        self.contentView.addSubviews([goalTitleLabel, ifSuccessLabelContainerView, menuBtn, spentMoneyTitleLabel, moneyGoalLabel, realSpentMoneyLabel,privateImageView, progressContainerView,ifSuccess
요기 콤마 뒤에 띄어쓰기가 있었다 없었다 하는데, 통일시켜줍시당!!

2022-07-08 16:37 UTC, jane1choi commented on POME-iOS/POME-iOS/Screen/Mypage/Cell/TVC/GoalStorageTVC.swift
> +            $0.width.equalToSuperview().multipliedBy(progress / 100)
캬~~굿굿!!!!

2022-07-08 16:37 UTC, jane1choi commented on POME-iOS/POME-iOS/Screen/Mypage/Cell/TVC/GoalStorageTVC.swift
> +    private func updateProgress(completion: @escaping () -> Void) {
요 함수도 문서화 해주면 좋을 것 같습니다!

2022-07-08 16:37 UTC, jane1choi commented on POME-iOS/POME-iOS/Screen/Mypage/Cell/TVC/GoalStorageTVC.swift
> +            }
로직처리 굿굿👏🏻

2022-07-08 16:37 UTC, jane1choi commented on POME-iOS/POME-iOS/Screen/Mypage/Cell/TVC/GoalStorageTVC.swift
> +            percentageContainerView.backgroundColor = .red
요거 `forEach` 사용해서 한줄로 줄여보는거 어떨까요??

2022-07-08 16:37 UTC, jane1choi commented on POME-iOS/POME-iOS/Screen/Mypage/Cell/TVC/GoalStorageTVC.swift
> +            percentageContainerView.backgroundColor = .main
요기두!

2022-07-09 07:35 UTC, wngus4296 requested changes
리뷰 반영 굿이네요! 은주언니가 말한 함수 문서화만 수정하고, 저 함수 네이밍만 한 번 체크해주세요!!

2022-07-09 07:35 UTC, wngus4296 commented on POME-iOS/POME-iOS/Screen/Mypage/Cell/TVC/GoalStorageTVC.swift
> +    func cellColor() {
요 함수 네이밍  configure~로 바꾸면 조금 더 직관적일 수도 있을 것 같아요.!.!

2022-07-09 07:42 UTC, yujindonut commented on POME-iOS/POME-iOS/Screen/Mypage/Cell/TVC/GoalStorageDataModel.swift
> +struct GoalDataModel {
아 !! 감사합니다 은주선배 .. 🥹 꼼꼼 그 자체 ..

2022-07-09 07:42 UTC, yujindonut commented on POME-iOS/POME-iOS/Screen/Mypage/Cell/TVC/GoalStorageTVC.swift
> +    var progress = 1.0
아항 !! 맞아요 !! private처리!!🥹
은주 선배 감사합니다 ..🫶

2022-07-09 07:42 UTC, yujindonut commented on POME-iOS/POME-iOS/Screen/Mypage/Cell/TVC/GoalStorageTVC.swift
> +    }
기본 폴더셋팅을 너무 잘해준 .. 은주 덕분에 ..🫶

2022-07-09 07:42 UTC, yujindonut commented on POME-iOS/POME-iOS/Screen/Mypage/Cell/TVC/GoalStorageTVC.swift
> +    override func setSelected(_ selected: Bool, animated: Bool) {
띄고 커밋 다시 할게용 ❤️‍🔥 말해주셔서 감사해요 주현시❤️

2022-07-09 07:42 UTC, yujindonut commented on POME-iOS/POME-iOS/Screen/Mypage/Cell/TVC/GoalStorageTVC.swift
> +        self.contentView.addSubviews([goalTitleLabel, ifSuccessLabelContainerView, menuBtn, spentMoneyTitleLabel, moneyGoalLabel, realSpentMoneyLabel,privateImageView, progressContainerView,ifSuccess
띄어쓰는걸로 통일했습니다 🫶

2022-07-09 07:42 UTC, yujindonut commented on POME-iOS/POME-iOS/Screen/Mypage/Cell/TVC/GoalStorageTVC.swift
> +    private func updateProgress(completion: @escaping () -> Void) {
은주님 .. 함수 문서화가 혹쉬 어떤걸 말씀해주시는건가요 .. 
찾아보니 swift 함수 문서화로 찾으니 .. 주석 문서화만 .. 나오네요 .. 🥹

2022-07-09 07:42 UTC, yujindonut commented on POME-iOS/POME-iOS/Screen/Mypage/Cell/TVC/GoalStorageTVC.swift
> +            percentageContainerView.backgroundColor = .red
그 프로퍼티가 .. 각각 달라도 for each문을 사용할 수 있나요?! . . !!!!!!!!

2022-07-09 07:42 UTC, yujindonut commented on POME-iOS/POME-iOS/Global/Struct/Identifiers.swift
> +    static let GoalStorageTVC = "GoalStorageTVC"
네이밍을 다시 변경해서 수정올리도록 할게여!!!

2022-07-09 07:42 UTC, jane1choi commented on POME-iOS/POME-iOS/Screen/Mypage/Cell/TVC/GoalStorageTVC.swift
> +    private var progress = 1.0
여기 위에 // MARK: Properties 주석 하나 추가하자!!

2022-07-09 07:44 UTC, yujindonut commented on POME-iOS/POME-iOS/Screen/Mypage/Cell/TVC/GoalStorageTVC.swift
> +    func cellColor() {
요기 부분은 그 viewcontroller부분에서 수정가능하도록 하는게 더 나을것 같아서 뒤에 풀 올린거는 뺐슴니다.. !!!!! 
다음부터 configure로 올리도록 할게요❤️

2022-07-09 07:44 UTC, wngus4296 commented on POME-iOS/POME-iOS/Screen/Mypage/Cell/TVC/GoalStorageTVC.swift
> +    func cellColor() {
넹 ❤️

2022-07-09 08:08 UTC, wngus4296 requested changes
여기...만... 진짜 마지막입니다...

2022-07-09 08:08 UTC, wngus4296 commented on POME-iOS/POME-iOS/Screen/Mypage/Cell/TVC/GoalCardTVC.swift
> +
언니 .. 여기 진짜 마지막

2022-07-09 08:09 UTC, yujindonut commented on POME-iOS/POME-iOS/Screen/Mypage/Cell/TVC/GoalCardTVC.swift
> +
진짜 내가 미안해..

2022-07-09 08:14 UTC, jane1choi approved these changes, later dismissed
화긴~ 컨벤션은 주혀니한테 맡길게 ㅋㅎㅋㅎㅋㅎ
유지니 수고많았어!!

2022-07-09 08:14 UTC, wngus4296 approved these changes
어푸룹드립니다 
코베 처음이라 힘들었을텐데 고생했어요!!!!!!!!!!

2022-07-09 08:19 UTC, wngus4296 requested changes
제가 더 꼼꼼하게 볼게요... 찐막...

2022-07-09 08:19 UTC, wngus4296 commented on POME-iOS/POME-iOS/Screen/Mypage/Cell/TVC/GoalCardTVC.swift
> +
193번 빈줄 삭제하구

2022-07-09 08:19 UTC, wngus4296 commented on POME-iOS/POME-iOS/Screen/Mypage/Cell/TVC/GoalCardTVC.swift
> +        else {
여기 
```
if {
} else {
}
```
이렇게 바꿔주시면.. 좋을 것 같습니다..

2022-07-09 08:19 UTC, wngus4296 commented on POME-iOS/POME-iOS/Screen/Mypage/Cell/TVC/GoalCardTVC.swift
> +
여기 밑에도 addSubview라 빈줄은 삭제해도 될 것 같은데,, 이건 사실 헷갈리네요 ㅋㅎ..

2022-07-09 08:23 UTC, wngus4296 approved these changes
최고다 최고.

2022-07-09 08:25 UTC, jane1choi approved these changes
주현이 믿겠습니다~! 유지니 수고해써~!!!

2022-07-09 08:26 UTC, merged