✨ [FEAT] 친구탭 생성
TeamPOME/POME-iOS pull request #35
Opened 2022-07-11 14:37 UTC by yujindonut

```
- commit message가 적절한지 확인해주세요.
- 마지막으로 Coding Convention을 준수했는지 확인해주세요.
- 적절한 branch로 요청했는지 확인해주세요.
- Assignees, Label을 붙여주세요.
- 가능한 이슈를 Link 해주세요.
- PR이 승인된 경우 해당 브랜치는 삭제 부탁드립니다.
```

## 🍎 관련 이슈
closed #18 

## 🍎 변경 사항 및 이유

- 친구 없을 때 셀
- empty cell 생성
- collection view 생성
- tableview 생성

## 🍎 PR Point

- 친구가 있을 때 없을때를 구분해서 셀이 보이게 구현해주었습니다.
- 위에 콜렉션 뷰가 스크롤 되지 않도록 수정해주었습니다.
- 전체가 클릭되었을때와, 친구가 클릭되었을때 이미지를 변경할 수 있도록 해주었습니다.

```Swift
func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        guard let cell = mateProfileCV.dequeueReusableCell(withReuseIdentifier: Identifiers.MateHeaderCVC, for: indexPath) as? MateHeaderCVC else {
            return UICollectionViewCell()
        }
        
        /// 셀이 선택되었을때, 글씨체 설정
        if indexPath.row == selectedIndex {
            cell.nameLabel.textColor = .grey_9
            cell.nameLabel.font = UIFont.PretendardSB(size: 12)
        }
        else {
            cell.nameLabel.textColor = .grey_5
            cell.nameLabel.font = UIFont.PretendardM(size: 12)
        }
        
        /// 전체보기 버튼 이미지 설정
        if indexPath.row == 0 {
            if selectedIndex == 0 {
                cell.profileImageView.image = UIImage(named: "btnAllViewProfileClicked")
            } else {
                cell.profileImageView.image = UIImage(named: "btnAllViewProfileNotClicked")
            }
        }
        else {
            cell.profileImageView.image = UIImage(named: "userProfileFill32")
        }
        
        return cell
    }
```

## 📸 ScreenShot
- 친구가 1명 이상일때

![Simulator Screen Recording - iPhone 12 - 2022-07-11 at 23 36 04](https://user-images.githubusercontent.com/78431728/178289452-63d722f5-2eff-4d3a-892b-f6796d68e09d.gif)

- 친구가 0명일때
![Simulator Screen Recording - iPhone 12 - 2022-07-11 at 22 53 57](https://user-images.githubusercontent.com/78431728/178288934-4f0be156-061b-4f47-a8e0-0beca3f9d73f.gif)

- 친구 셀을 클릭했을 때
![Simulator Screen Recording - iPhone 12 - 2022-07-11 at 23 35 36](https://user-images.githubusercontent.com/78431728/178289338-49f1ccf6-9b31-43af-809f-25d67e4f2543.gif)

2022-07-11 15:34 UTC, wngus4296 requested changes
굿걸..~ 리뷰 한 번 확인해주세여~~

2022-07-11 15:34 UTC, wngus4296 commented on POME-iOS/POME-iOS/Screen/Mate/Cell/TVC/HaveMateTVC.swift
> +    }
이 친구는 UI로 가는 게 어떨까요?!

2022-07-11 15:34 UTC, wngus4296 commented on POME-iOS/POME-iOS/Screen/Mate/VC/MateVC.swift
> +}
함수들 모두 간단하게 문서화 해주는 건 어떨까요 ?!

2022-07-11 15:34 UTC, wngus4296 commented on POME-iOS/POME-iOS/Screen/Mate/VC/MateVC.swift
> +        else {
else를 위로 붙입시다~!~!

2022-07-11 15:34 UTC, wngus4296 commented on POME-iOS/POME-iOS/Screen/Mate/VC/MateVC.swift
> +        else {
```
cell.nameLabel.textColor = (indexPath.row == selectedIndex) ? .grey_9 : .grey_5
cell.nameLabel.font = (indexPath.row == selectedIndex) ? UIFont.PretendardSB(size: 12) : UIFont.PretendardM(size: 12)
```

조심스럽게 제안해봅니다..

2022-07-11 15:36 UTC, jane1choi requested changes
유지나 넘 수고했어!!!!
리뷰 확인 부탁할게~!

2022-07-11 15:36 UTC, jane1choi commented on POME-iOS/POME-iOS/Screen/Mate/Cell/CVC/MateHeaderCVC.swift
> +extension MateHeaderCVC {
`// MARK: - UI` 추가해주세요~!

2022-07-11 15:36 UTC, jane1choi commented on POME-iOS/POME-iOS/Screen/Mate/Cell/TVC/HaveMateTVC.swift
> +    private func setLabelLine() {
custom method에는 문서화 주석 넣어주면 좋을 것 같아요~!

2022-07-11 15:36 UTC, jane1choi commented on POME-iOS/POME-iOS/Screen/Mate/Cell/TVC/HaveNoMateTVC.swift
> +    override func setViews() {
// MARK: - Life Cycle 추가해주세요!

2022-07-11 15:36 UTC, jane1choi commented on POME-iOS/POME-iOS/Screen/Mate/Cell/TVC/HaveNoMateTVC.swift
> +    private let allContainerView = UIView().then {
네이밍 `containerView`로 수정하면 좋을 것 같아요!!!

2022-07-11 15:36 UTC, jane1choi commented on POME-iOS/POME-iOS/Screen/Mate/VC/MateVC.swift
> +    private func setTV(){
registerTVC로 함수 네이밍 변경해주는게 좋을 것 같습니다!!

2022-07-11 15:36 UTC, jane1choi commented on POME-iOS/POME-iOS/Screen/Mate/VC/MateVC.swift
> +    }
문서화 해주세요...

2022-07-11 15:36 UTC, jane1choi commented on POME-iOS/POME-iOS/Screen/Mate/VC/MateVC.swift
> +            if selectedIndex == 0 {
요부분 
```Swift
if indexPath.row == 0 && selectedIndex == 0 { code } 
```
로 바꿔줘도 될 것 같네요!!

2022-07-11 15:36 UTC, jane1choi commented on POME-iOS/POME-iOS/Screen/Mate/VC/MateVC.swift
> +        return 18.adjusted
큰 기기에서 간격 너무 넓게 나오지는 않은지 확인부탁드립니다!!

2022-07-11 17:10 UTC, yujindonut commented on POME-iOS/POME-iOS/Screen/Mate/VC/MateVC.swift
> +        else {
바로 바꿔버리겟슴니다 . 🫶

2022-07-11 17:16 UTC, yujindonut commented on POME-iOS/POME-iOS/Screen/Mate/VC/MateVC.swift
> +    private func setTV(){
콜렉션 셀도 있어서 registerCell로 변경하도록 하겠씁니다!!!!!🥹

2022-07-12 04:49 UTC, jane1choi commented on POME-iOS/POME-iOS/Screen/Mate/Cell/TVC/HaveMateTVC.swift
> +    }
요 함수 세개 `configureUI()` 함수 하나로 합쳐도 좋을 것 같아!!!

2022-07-12 05:29 UTC, wngus4296 approved these changes
확인했어요 고생하셨습니당 ~~

2022-07-12 05:33 UTC, jane1choi commented on POME-iOS/POME-iOS/Screen/Mate/VC/MateVC.swift
> +        mateTV.isScrollEnabled = (mateNum == 0) ? false : true
굳!

2022-07-12 05:39 UTC, jane1choi approved these changes
유진아 넘 고생했는데!! 
코드를 다 짜고 나서 컨벤션 맞춰서 수정하려고 하면 수정해야할 게 잘 안보이니까
컨벤션에 맞춰 코드를 짜는 습관을 들이자..!

다음부턴 컨벤션 관련해서 코드리뷰와 수정에 많은 시간을 들이는 일이 없도록 합시다!!!!

2022-07-12 05:39 UTC, jane1choi commented on POME-iOS/POME-iOS/Support/SceneDelegate.swift
> +            window.rootViewController = UIStoryboard.init(name: "SignSB", bundle: nil).instantiateViewController(withIdentifier: MakeProfileVC.className) as? MakeProfileVC
굳굳

2022-07-12 05:45 UTC, wngus4296 commented on POME-iOS/POME-iOS/Support/SceneDelegate.swift
> +            window.rootViewController = UIStoryboard.init(name: "SignSB", bundle: nil).instantiateViewController(withIdentifier: MakeProfileVC.className) as? MakeProfileVC
주의하겠습니다.....

2022-07-12 05:45 UTC, merged