✨ [FEAT] 목표 추가 뷰 UI 구현
TeamPOME/POME-iOS pull request #64
Opened 2022-07-17 16:12 UTC by wngus4296

## 🍎 관련 이슈
closed #56 

## 🍎 변경 사항 및 이유
* 목표 추가 뷰 플로우 모두 구현하였습니다.
* 나눠서 pr 올렸어야 하는데... 죄송합니다...

## 🍎 PR Point
* UIViewController+ 익스텐션에 날짜를 포멧 형태에 따라 변경해주는 메서드를 추가하였습니다.
``` swift
    /// 년, 월 형식으로 리턴하는 함수
    func getMonthDate(date: Date) -> String {
        let df = DateFormatter()
        df.locale = Locale(identifier: "ko_KR")
        df.dateFormat = "yyyy년 M월"
        return df.string(from: date)
    }
    
    /// yyyy.MM.dd 형식으로 리턴하는 함수
    func getSelectedDate(date: Date) -> String {
        let df = DateFormatter()
        df.locale = Locale(identifier: "ko_KR")
        df.dateFormat = "yyyy.MM.dd"
        return df.string(from: date)
    }
    
    /// yyyy.MM.dd 형식의 날짜를 Date형으로 바꿔주는 함수
    func getStringToDate(string: String) -> Date {
        let df = DateFormatter()
        df.locale = Locale(identifier: "ko_KR")
        df.dateFormat = "yyyy.MM.dd"
        return df.date(from: string) ?? Date()
    }
```

### 캘린더
* 캘린더 헤더 부분 (버튼, yyyy년 mm달)은 fsCalendar로 커스텀이 불가능해서 uiview로 만들어주었습니다.
    * yyyy년 mm달은 현재 달력에 따라 text를 바꿔주었습니다. 
* 캘린더 좌우버튼 분기처리 (한 달 간격만 가능)
    * 시작 캘린더 띄울 때: 현재날짜 - 시작날짜 비교해서 같은 경우 왼쪽 버튼 비활성화, 다른 경우 오른쪽 버튼 비활성화
    * 종료 캘린더 띄울 때: 시작날짜 - 종료날짜 비교해서 같은 경우 왼쪽 버튼 비활성화, 다른 경우 오른쪽 버튼 비활성화
    * 좌우 버튼 중 하나라도 누를때마다 toggle() 해주었습니다.
* 캘린더 활성화 날짜 분기 처리
    * 시작 캘린더 띄울 때: 시작날짜가 없는 경우 오늘날짜 전달, 시작날짜가 있는 경우 해당 날짜 전달 (default 설정 때문)
    * 종료 캘린더 띄울 때: 종료날짜가 없는 경우 시작날짜의 다음 날 전달, 종료날짜 있는 경우 해당날짜 전달 (default 설정 때문)
    * 시작 & 종료 날짜 둘 다 있어야 하단 버튼 활성화

### 내용 (textfield 있는 부분)
* 글자수 제한을 각각 해주었습니다.
* 금액은 키보드가 내려갈 때 세자리마다 콤마가 들어가도록 했습니다.
* 리턴을 누를 때 다음 칸이 비어있을 경우 자동으로 커서가 움직이게 했습니다. 만약 다음칸이 차있을 경우 키보드가 내려갑니다.
    * 만약 2칸은 채워져있고 3칸은 비어있을 때 1칸에서 리턴을 누르면 자동으로 3칸으로 이동합니다.

## 📸 ScreenShot
![Simulator Screen Recording - iPhone 11 - 2022-07-18 at 00 56 32](https://user-images.githubusercontent.com/58043306/179407726-2abd9a24-00d6-4d36-a0dd-a1fef10abd93.gif)

2022-07-17 17:00 UTC, jane1choi requested changes
분기처리 대박 꼼꼼한거 머야 진짜...
치타처럼 빠른 천개 아닌지,,, 증맬 고생많았어!!
시간날 때 리뷰확인한번 해조~!

2022-07-17 17:00 UTC, jane1choi commented on POME-iOS/POME-iOS/Global/Extension/UIViewController+.swift
> +    }
아주 굿입니다~!

2022-07-17 17:00 UTC, jane1choi commented on POME-iOS/POME-iOS/Screen/Write/VC/AddGoalContentVC.swift
> +    }
이 함수도 다른 곳에서 쓰일 수 있을 것 같아서 `UIViewController+` extension 파일에 public 함수로 빼두면 좋을 것 같아요~!

2022-07-17 17:00 UTC, jane1choi commented on POME-iOS/POME-iOS/Screen/Write/VC/AddGoalContentVC.swift
> +    }
이 함수도 다른 곳에서 쓰일 수 있을 것 같아서 `UITextfield+` extension 파일에 public 함수로 빼두면 textfield 파라미터 없이 maxLength만 지정해서 사용해줄 수 있을 것 같아요!!

2022-07-17 17:00 UTC, jane1choi commented on POME-iOS/POME-iOS/Screen/Write/VC/AddGoalContentVC.swift
> +        }
굳굳!! 천재가 아닌지,,,,

2022-07-17 17:00 UTC, jane1choi commented on POME-iOS/POME-iOS/Screen/Write/Xib/CalendarVC.swift
> +    var delegate: DeliveryDateDelegate?
프로젝트 내에서 delegate가 곳곳에서 많이 쓰이니 `delegate` 변수명도 직관적으로 네이밍으로 변경해주면 좋을 것 같습니다!!

2022-07-17 17:12 UTC, yujindonut approved these changes, later dismissed
주현아 그냥 너무 고생했어 .. .. 진짜로 .. .. .. .. .. 주현아 제발쉬어줘 ... plz .....

2022-07-17 17:12 UTC, yujindonut commented on POME-iOS/POME-iOS/Screen/Write/VC/AddGoalContentVC.swift
> +    /// 글자수 제한 함수
글자수 제한까지????????? 주현이 걍 예외처리 .. 천개 ~ ..

2022-07-17 17:12 UTC, yujindonut commented on POME-iOS/POME-iOS/Screen/Write/VC/AddGoalContentVC.swift
> +    /// 세 자리마다 콤마를 넣음
진짜 자란다 변주현 .. 자란다..

2022-07-17 17:12 UTC, yujindonut commented on POME-iOS/POME-iOS/Screen/Write/VC/AddGoalContentVC.swift
> +            priceTextField.text = numberFormatter(number: price)
진심 꼼꼼해 변주현 .. 대박이야 ..

2022-07-17 17:12 UTC, yujindonut commented on POME-iOS/POME-iOS/Screen/Write/VC/AddGoalContentVC.swift
> +        if !categoryTextField.isEmpty && !promiseTextField.isEmpty && !priceTextField.isEmpty {
예외처리 굿...❤️

2022-07-17 17:12 UTC, yujindonut commented on POME-iOS/POME-iOS/Screen/Write/VC/AddGoalDateVC.swift
> +        /// 선택된 값 유무에 따라 시작 날짜 전달 선택하지 않았으면 오늘 날짜 전달
와 걍 미침 .. 굿굿 ..

2022-07-17 17:12 UTC, yujindonut commented on POME-iOS/POME-iOS/Screen/Write/VC/AddGoalDateVC.swift
> +        /// 선택된 값 유무에 따라 종료 날짜 전달 선택하지 않았으면 시작 날짜의 다음 날짜 전달
굿굿 .. 걍.. 미쳤어 .. 변즈현코드는 다 예외처리 가능 ..

2022-07-17 17:12 UTC, yujindonut commented on POME-iOS/POME-iOS/Screen/Write/VC/AddGoalDateVC.swift
> +        /// 날짜 두 개 다 선택한 경우 다음으로 넘어가는 버튼 활성화
진짜 .. 천개 천개 ..

2022-07-17 17:12 UTC, yujindonut commented on POME-iOS/POME-iOS/Screen/Write/VC/WriteVC.swift
> +//    private var category = Array<String>()
나중에 서버통신을 위한 주석인가요~?

2022-07-17 17:12 UTC, yujindonut commented on POME-iOS/POME-iOS/Screen/Write/Xib/CalendarVC.swift
> +class CalendarVC: BaseVC {
걍 이름부터가 멋지다 주현아 ..

2022-07-17 17:12 UTC, yujindonut commented on POME-iOS/POME-iOS/Screen/Write/VC/AddGoalDateVC.swift
> +            guard let nextDay = Calendar.current.date(byAdding: .day, value: 1, to: self.getStringToDate(string: startDateLabel.text!)) else { return }
이거는 어떤 코드인지 여쭤봐도 될까요~?..?  현재 스타드 데이트 텍스트에 하루를 더해주는 코드인건가요~?

2022-07-17 17:12 UTC, yujindonut commented on POME-iOS/POME-iOS/Screen/Write/Xib/CalendarVC.swift
> +        if isStartCalendar {
여기서 if isStartCalendar를 써주는 이유는 무엇인가요~?

2022-07-17 17:12 UTC, yujindonut commented on POME-iOS/POME-iOS/Screen/Write/Xib/WriteBottomAlertVC.swift
>              DispatchQueue.main.async {
비동기식 처리를 사용해야하는 이유는 무엇인가요 ~? ~? ~? ..

2022-07-18 05:20 UTC, wngus4296 commented on POME-iOS/POME-iOS/Screen/Write/VC/WriteVC.swift
> +//    private var category = Array<String>()
분기처리 확인용입니다! 두 가지 경우를 확인할 일이 많아서 넣어놨고 서버 통신 때 삭제할 코드입니다~!

2022-07-18 05:21 UTC, wngus4296 commented on POME-iOS/POME-iOS/Screen/Write/VC/AddGoalDateVC.swift
> +            guard let nextDay = Calendar.current.date(byAdding: .day, value: 1, to: self.getStringToDate(string: startDateLabel.text!)) else { return }
넹 맞습니다!! byAdding에 .day, .month. .year 이런식으로 적어줄 수 있어요!

2022-07-18 05:22 UTC, wngus4296 commented on POME-iOS/POME-iOS/Screen/Write/Xib/CalendarVC.swift
> +        if isStartCalendar {
시작날짜 캘린더인 경우 무조건 오늘부터 한 달 뒤 까지만 보여줘야하고 (고정)
종료날짜 캘린더인 경우 선택한 시작날짜로부터 한 달 뒤 까지만 보여줘야하기 때문에 (고정x) 나눠준겁니당

2022-07-18 05:22 UTC, wngus4296 commented on POME-iOS/POME-iOS/Screen/Write/Xib/WriteBottomAlertVC.swift
>              DispatchQueue.main.async {
비동기식 처리를 안하면 ui업데이트가 안되어서 써줬습니당 !

2022-07-18 07:30 UTC, jane1choi approved these changes
굳굳 확인했습니당!! 수고해써!

2022-07-18 07:36 UTC, merged